# Generated by Django 5.0.2 on 2024-02-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTraker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.CharField(default='paaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('restaurant', 'Restaurant'), ('gift', 'Gift'), ('electronics', 'Electronics'), ('supplies', 'Supplies'), ('repair', 'Repair'), ('social', 'Social Life'), ('clothing', 'Clothing'), ('cosmetics', 'Cosmetics'), ('medicine', 'Medicine')], default='', max_length=100),
        ),
    ]
