# Generated by Django 5.0.2 on 2024-03-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTraker', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
